apiVersion: v1
kind: Pod 
metadata: 
  name: openam-pod
  labels: 
    app: openam
    type: sso-server
spec:
  hostAliases:
   - ip: "192.168.56.5"
     hostnames:
      - "openam1.example.com"
      - "ldap.example.com"
   - ip: "192.168.56.5"
     hostnames:
      - "web.example.com"
  containers: 
   - name: openam-container
     image: openam:v3
