apiVersion: v1
kind: Service
metadata:
  name: am-service
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30010
  selector:
    app: openam
    type: sso-server
